import mongoose from "mongoose";

// Submission question answer schema
const answerSchema = new mongoose.Schema(
    {
        questionId: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
        },
        answer: {
            type: mongoose.Schema.Types.Mixed, // String for text, number for MCQ, code for coding
        },
        // For coding questions
        code: String,
        language: String,
        // Test case results
        testResults: [{
            input: String,
            expected: String,
            actual: String,
            passed: Boolean,
            executionTime: Number,
            error: String,
        }],
        // Scoring
        points: {
            type: Number,
            default: 0,
        },
        maxPoints: Number,
        isCorrect: Boolean,
        // Time tracking
        timeSpent: {
            type: Number, // seconds
            default: 0,
        },
        // Flagged for review
        flagged: {
            type: Boolean,
            default: false,
        },
    },
    { _id: true }
);

// Proctoring event schema
const proctoringEventSchema = new mongoose.Schema(
    {
        type: {
            type: String,
            enum: [
                "tab_switch",
                "window_blur",
                "fullscreen_exit",
                "face_not_visible",
                "multiple_faces",
                "suspicious_audio",
                "copy_paste",
                "right_click",
            ],
        },
        timestamp: {
            type: Date,
            default: Date.now,
        },
        details: String,
        screenshot: String, // URL if captured
    },
    { _id: true }
);

// Main Assessment Submission Schema
const assessmentSubmissionSchema = new mongoose.Schema(
    {
        // References
        assessment: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Assessment",
            required: true,
            index: true,
        },
        candidate: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true,
        },
        application: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Application",
            index: true,
        },
        company: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Company",
            required: true,
        },
        // Invited by
        invitedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
        },
        invitedAt: Date,
        // Status
        status: {
            type: String,
            enum: [
                "invited",
                "started",
                "in_progress",
                "submitted",
                "expired",
                "cancelled",
                "graded",
            ],
            default: "invited",
            index: true,
        },
        // Timing
        startedAt: Date,
        submittedAt: Date,
        deadline: Date,
        timeTaken: {
            type: Number, // seconds
            default: 0,
        },
        // Answers
        answers: [answerSchema],
        // Scoring
        score: {
            type: Number,
            default: 0,
        },
        maxScore: {
            type: Number,
            default: 0,
        },
        percentage: {
            type: Number,
            default: 0,
        },
        passed: {
            type: Boolean,
        },
        rank: Number, // Relative rank among all submissions
        // Proctoring
        proctoring: {
            enabled: { type: Boolean, default: false },
            events: [proctoringEventSchema],
            tabSwitches: { type: Number, default: 0 },
            suspiciousActivity: { type: Boolean, default: false },
            trustScore: { type: Number, default: 100 },
        },
        // Browser info
        browserInfo: {
            userAgent: String,
            platform: String,
            screenResolution: String,
            ipAddress: String,
        },
        // Feedback
        feedback: {
            recruiter: {
                notes: String,
                rating: { type: Number, min: 1, max: 5 },
                reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
                reviewedAt: Date,
            },
            autoGenerated: {
                summary: String,
                strengths: [String],
                improvements: [String],
            },
        },
    },
    {
        timestamps: true,
    }
);

// Indexes
assessmentSubmissionSchema.index({ assessment: 1, candidate: 1 }, { unique: true });
assessmentSubmissionSchema.index({ status: 1, createdAt: -1 });
assessmentSubmissionSchema.index({ company: 1, status: 1 });
assessmentSubmissionSchema.index({ percentage: -1 });

// Virtual for time remaining (if in progress)
assessmentSubmissionSchema.virtual("timeRemaining").get(function () {
    if (this.status !== "in_progress" || !this.startedAt) return 0;
    const elapsed = (Date.now() - this.startedAt.getTime()) / 1000;
    const duration = this.assessment?.duration * 60 || 3600;
    return Math.max(0, duration - elapsed);
});

// Method to start assessment
assessmentSubmissionSchema.methods.start = function () {
    this.status = "in_progress";
    this.startedAt = new Date();
    return this.save();
};

// Method to submit assessment
assessmentSubmissionSchema.methods.submit = async function () {
    this.status = "submitted";
    this.submittedAt = new Date();
    this.timeTaken = Math.floor((this.submittedAt - this.startedAt) / 1000);

    // Calculate score
    let totalScore = 0;
    let maxScore = 0;

    this.answers.forEach((ans) => {
        totalScore += ans.points || 0;
        maxScore += ans.maxPoints || 0;
    });

    this.score = totalScore;
    this.maxScore = maxScore;
    this.percentage = maxScore > 0 ? Math.round((totalScore / maxScore) * 100) : 0;

    return this.save();
};

// Method to record proctoring event
assessmentSubmissionSchema.methods.recordProctoringEvent = function (type, details) {
    this.proctoring.events.push({ type, details, timestamp: new Date() });

    if (type === "tab_switch") {
        this.proctoring.tabSwitches += 1;
    }

    // Reduce trust score based on event severity
    const severityMap = {
        tab_switch: 5,
        window_blur: 3,
        fullscreen_exit: 10,
        face_not_visible: 15,
        multiple_faces: 20,
        copy_paste: 10,
    };

    this.proctoring.trustScore = Math.max(0, this.proctoring.trustScore - (severityMap[type] || 5));

    if (this.proctoring.trustScore < 50) {
        this.proctoring.suspiciousActivity = true;
    }

    return this.save();
};

// Ensure virtuals are included
assessmentSubmissionSchema.set("toJSON", { virtuals: true });
assessmentSubmissionSchema.set("toObject", { virtuals: true });

export const AssessmentSubmission = mongoose.model(
    "AssessmentSubmission",
    assessmentSubmissionSchema
);
